position = "Bottom"

[modules]
left = [ "Workspaces", "WindowTitle", "MediaPlayer" ]
right = [ "KeyboardLayout", "SystemInfo", "Tray", "Privacy", "Clock", "Settings" ]

[appearance]
style = "Solid"

[appearance.background_color]
base = "#000000"
