position = "Bottom"

[modules]
left = [ "Workspaces", "WindowTitle" ]
center = [ "MediaPlayer" ]
right = [ "SystemInfo", "Tray", "Clock", "Privacy", "Settings" ]

[system_info]
indicators = [ "Cpu", "Temperature", "Memory" ]

[appearance]
style = "Solid"

[appearance.background_color]
base = "#000000"
